### ISSUE TITLE
Use the auto flattening of the data to make a connection and add new form

### ISSUE THREAD

**Issue by siddhant3030** [DalgoT4D/dbt_stir#16]
We need to adapt the DBT once we start pulling the raw data and there is a new form for Ethiopia which needs to be pulled 
This required changes certain files 

1. [int_classroom_surveys_delhi.sql](https://github.com/DalgoT4D/dbt_stir/blob/main/models/intermediate/classroom_surveys/int_classroom_surveys_delhi.sql)

2. [int_classroom_surveys_indonesia.sql](https://github.com/DalgoT4D/dbt_stir/blob/main/models/intermediate/classroom_surveys/int_classroom_surveys_indonesia.sql)

3. [int_classroom_surveys_karnataka.sql](https://github.com/DalgoT4D/dbt_stir/blob/main/models/intermediate/classroom_surveys/int_classroom_surveys_karnataka.sql) 

4. [int_classroom_surveys_tamil_nadu.sql](https://github.com/DalgoT4D/dbt_stir/blob/main/models/intermediate/classroom_surveys/int_classroom_surveys_tamil_nadu.sql) 

5. [int_classroom_surveys_uganda.sql](https://github.com/DalgoT4D/dbt_stir/blob/main/models/intermediate/classroom_surveys/int_classroom_surveys_uganda.sql) 

After this we need to do add one more file called int_classroom_surveys_ethiopia and follow the same thing which we have in this files. Then push that to aggregated and prod tables.

**Comment by Abhishek-N** [comment]
1. Add new form `ethiopia_stir_bm_202324` and sync
2. Add new model for ethiopia and make the relevant changes
3. Update `ethiopia_stir_bm_202324` with `classroom_surveys_merged` model
