### ISSUE TITLE
- Behavioral breakdown tab -> saftey | students chart

### ISSUE THREAD

**Issue by siddhant3030** [DalgoT4D/dbt_stir#22]
move this one also in dbt model. please check the sheet if it has the right calculation 

these are cases which you will also find in the query. 

cro1 - Not ridiculed, yelled at
cro2 - Not punished physically
cro3 - Acknowledged for effort

**Comment by Abhishek-N** [comment]
Fix: https://github.com/DalgoT4D/dbt_stir/pull/37
